bilelmoussaoui/ashpd

- Cargo.toml
- demo/Cargo.toml
- demo/src/main.rs
- src/desktop/account.rs
- src/desktop/background.rs
- src/desktop/camera.rs
- src/desktop/device.rs
- src/desktop/email.rs
- src/desktop/file_chooser.rs
- src/desktop/inhibit.rs
- src/desktop/location.rs
- src/desktop/network_monitor.rs
- src/desktop/notification.rs
- src/desktop/open_uri.rs
- src/desktop/print.rs
- src/desktop/remote_desktop.rs
- src/desktop/screencast.rs
- src/desktop/screenshot.rs
- src/desktop/secret.rs
- src/desktop/trash.rs
- src/desktop/wallpaper.rs
- src/documents/document.rs
- src/documents/file_transfer.rs
- src/flatpak/mod.rs
- src/flatpak/update_monitor.rs
- src/lib.rs
- src/request.rs
- src/session.rs
- src/window_identifier.rs
> WIP: Finish the basics

- README.md
- src/desktop/open_uri.rs
- src/desktop/remote_desktop.rs
- src/desktop/screencast.rs
- src/documents/mod.rs
> Prepare for a new release

- src/window_identifier.rs
See https://github.com/gtk-rs/gtk4-rs/pull/786
> window_identifier: Update for return value nullability changes

- src/window_identifier.rs
This way we always return a valid handle even if the WindowIdentifier is constructed multiple times
from different calls
Closes #20 
Supersedes #21 
cc @Cogitri 
This is barely a work around, and it will still fail because the moment the first window identifier is dropped, the handle will no longer be valid because it has been un-exported after that. I think we can work around that issue as well, by storing a refcount and only unexport if that refcount is equal to 1. Edit: fixed
Before I do the rest of that, I was wondering what do you think of this approach? If all sounds good to you, I will implement the rest, test it on ashpd-demo and push it as part of 0.2.2 release.
> window identifier: store the wayland handle in the object data

- src/desktop/secret.rs
It seems like the portal doesn't make use of the token at all
nor it returns it in future calls...
something to investigate
> Secret: Use a basic response

- Cargo.toml
- src/desktop/dynamic_launcher.rs
- src/desktop/icon.rs
- src/desktop/mod.rs
https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-org.freedesktop.portal.DynamicLauncher
TODO:
> desktop: Implement DynamicLauncher portal proxy

- Cargo.toml
- README.md
- ashpd-demo/Cargo.toml
- src/desktop/camera.rs
- src/desktop/request.rs
- src/desktop/screenshot.rs
- src/desktop/secret.rs
- src/desktop/session.rs
- src/helpers.rs
- src/lib.rs
- src/window_identifier/mod.rs
- src/window_identifier/wayland.rs
As it is, it requires either async-std or tokio which might be undesirable.
> Add option to use async-std or tokio

- Cargo.toml
- src/desktop/file_chooser.rs
- src/desktop/icon.rs
- src/desktop/open_uri.rs
- src/desktop/print.rs
- src/desktop/proxy_resolver.rs
- src/desktop/screenshot.rs
- src/desktop/wallpaper.rs
Fixes https://github.com/bilelmoussaoui/ashpd/issues/69
> Use url crate to handle uris

- ashpd-demo/Cargo.lock
- ashpd-demo/Cargo.toml
- ashpd-demo/src/portals/desktop/file_chooser.rs
- ashpd-demo/src/portals/desktop/open_uri.rs
- ashpd-demo/src/portals/desktop/proxy_resolver.rs
- ashpd-demo/src/portals/desktop/screenshot.rs
- ashpd-demo/src/portals/desktop/wallpaper.rs
Continuation of https://github.com/bilelmoussaoui/ashpd/pull/78.
> demo: Use url::Url

- Cargo.toml
- src/window_identifier/mod.rs
> Don't directly depend on zvariant

- ashpd-demo/Cargo.lock
- ashpd-demo/Cargo.toml
- ashpd-demo/src/widgets/gst_paintable.rs
- Update crates
- wip: paintable gl update
> Paintable GL

- ashpd-demo/src/widgets/gst_paintable.rs
We only need it for the non-gl path, glsinkbin includes a
glcolorconvert internally.
> widgets/gst_paintable: drop extra videoconvert element

- src/desktop/settings.rs
Since future setting keys might be fixed we allow both value(value(x)) and value(x).
> settings: Fix xdp bug on our side

- src/documents/mod.rs
Some of these functions accept an empty string, but calling with that was erroring since those are not valid as app ids. So accepting an `Option` would be idiomatic in Rust.
It could take `Option<T>` where `T` has a `TryFrom` bound, but that's an awkward API to deal with, since `None` can't be passed without a type. It also seems unidiomatic to take a generic argument when the conversion is failable; it would be cleaner to leave failable conversion to the caller.
Fixes https://github.com/bilelmoussaoui/ashpd/issues/129.
> documents: Take `AppId` or `OptionAppId` instead of `TryInto` generic

- ashpd-demo/src/application.rs
- ashpd-demo/src/portals/desktop/account.rs
- ashpd-demo/src/portals/desktop/background.rs
- ashpd-demo/src/portals/desktop/camera.rs
- ashpd-demo/src/portals/desktop/device.rs
- ashpd-demo/src/portals/desktop/email.rs
- ashpd-demo/src/portals/desktop/file_chooser.rs
- ashpd-demo/src/portals/desktop/location.rs
- ashpd-demo/src/portals/desktop/network_monitor.rs
- ashpd-demo/src/portals/desktop/notification.rs
- ashpd-demo/src/portals/desktop/open_uri.rs
- ashpd-demo/src/portals/desktop/print.rs
- ashpd-demo/src/portals/desktop/proxy_resolver.rs
- ashpd-demo/src/portals/desktop/remote_desktop.rs
- ashpd-demo/src/portals/desktop/screencast.rs
- ashpd-demo/src/portals/desktop/screenshot.rs
- ashpd-demo/src/portals/desktop/secret.rs
- ashpd-demo/src/portals/desktop/wallpaper.rs
- ashpd-demo/src/widgets/portal_page.rs
- ashpd-demo/src/window.rs
> Handle OpenFile if a file uri is used

- .github/workflows/demo-ci.yml
- ashpd-demo/Cargo.lock
- ashpd-demo/Cargo.toml
- ashpd-demo/build-aux/com.belmoussaoui.ashpd.demo.Devel.json
- ashpd-demo/data/resources/ui/location.ui
- ashpd-demo/data/resources/ui/window.ui
- ashpd-demo/src/portals/desktop/location.rs
- ashpd-demo/src/window.rs
- src/window_identifier/mod.rs
>  demo: Switch to new adwaita widgets 

- Cargo.toml
To help with testing latest bindings
> gtk: Switch to git deps

- src/desktop/clipboard.rs
- src/desktop/handle_token.rs
- src/desktop/mod.rs
- src/desktop/session.rs
- src/documents/mod.rs
> Add clipboard portal support

- src/desktop/remote_desktop.rs
admittedly this is untested but it *looks* correct :)
> desktop/remote_desktop: Add support for ConnectToEIS

- Cargo.toml
- src/desktop/clipboard.rs
- src/desktop/global_shortcuts.rs
- src/desktop/inhibit.rs
- src/desktop/location.rs
- src/desktop/memory_monitor.rs
- src/desktop/network_monitor.rs
- src/desktop/notification.rs
- src/desktop/session.rs
- src/desktop/settings.rs
- src/documents/file_transfer.rs
- src/flatpak/mod.rs
- src/flatpak/update_monitor.rs
- src/proxy.rs
> Expose streams for signals

- src/desktop/settings.rs
- src/proxy.rs
Follow up of #152 
Only works if rebased
> Add receive_color_scheme_changed_with_init

- src/lib.rs
As discussed in https://github.com/sonnyp/Workbench/pull/535#discussion_r1306705385
> Re-export url crate

- src/desktop/file_chooser.rs
<flatpak/xdg-desktop-portal#1045>
> filechooser: Support current_folder with OpenFile

- ashpd-demo/data/resources/ui/print.ui
There is no Inhibit method on the Print portal.
> print: Fix description

- src/desktop/color.rs
- src/desktop/settings.rs
Should the color fixes be applied to 0.7? I guess the change to `receive_accent_color_changed` is breaking, so I'm not sure.
> color fixes 0.8

- src/desktop/mod.rs
- src/desktop/remote_desktop.rs
- src/desktop/screencast.rs
> Add remote desktop persistence and session restore.

- ashpd-demo/Cargo.lock
- ashpd-demo/Cargo.toml
- ashpd-demo/src/portals/desktop/dynamic_launcher.rs
- ashpd-demo/src/portals/desktop/secret.rs
Also fix some clippy warnings.
> Port to ashpd 0.8

- src/desktop/clipboard.rs
- src/desktop/global_shortcuts.rs
- src/desktop/inhibit.rs
- src/desktop/input_capture.rs
- src/desktop/location.rs
- src/desktop/remote_desktop.rs
- src/desktop/screencast.rs
- src/desktop/session.rs
> session: Tie up portals to their corresponding sessions

- .github/workflows/backend-demo-ci.yml
- .gitignore
- Cargo.toml
- README.md
- backend-demo/Cargo.toml
- backend-demo/data/ashpd-backend-demo.portal
- backend-demo/src/account.rs
- backend-demo/src/main.rs
- backend-demo/src/screenshot.rs
- backend-demo/src/secret.rs
- backend-demo/src/wallpaper.rs
- src/app_id.rs
- src/backend/access.rs
- src/backend/account.rs
- src/backend/mod.rs
- src/backend/request.rs
- src/backend/screenshot.rs
- src/backend/secret.rs
- src/backend/settings.rs
- src/backend/wallpaper.rs
- src/desktop/account.rs
- src/desktop/color.rs
- src/desktop/mod.rs
- src/desktop/request.rs
- src/desktop/screenshot.rs
- src/desktop/settings.rs
- src/error.rs
- src/lib.rs
- src/window_identifier/mod.rs
> backend: Add basic support

- src/proxy.rs
> desktop/proxy: Properly propagate PortalError

- src/backend/request.rs
> backend: Always release a request even when it returns an error

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- src/backend/request.rs
- src/desktop/clipboard.rs
- src/desktop/icon.rs
> CI: install gstreamer
