bilelmoussaoui/ashpd

ashpd-demo/src/portals/desktop/screencast.rs

open_pipewire_remote returns fd

Very trivial fix

---

src/desktop/camera.rs
src/desktop/screencast.rs

`zbus` now closes file descriptors when the message is destroyed, unless if you use `OwnedFd`.

Use OwnedFd instead of Fd for returned file descriptors from zbus

---

Cargo.toml
README.md
src/window_identifier.rs

Fixes #40 
Still needs an API to get a Window Identifier from a RawWindowHandle.  Also needs a new release of gdk3wayland to expose the ffi crate

window identifier: provide a way API around raw-window-handle

---

src/desktop/screencast.rs

as it was added in the v3 of the interface
Fixes #48

screencast: mark source_type as optional

---

src/desktop/file_chooser.rs
src/documents/mod.rs
src/flatpak/mod.rs

I think the `Type` and `Serialize` parts of the `AsRef<Path> + Type + Serialize` weren't needed, because the path just gets turned into a byte slice anyway (which implements `Type` and `Serialize`).

Relax bounds for AsRef<Path>.

---

src/window_identifier.rs

This adds support for XCB in `from_raw_handle`, and it also allows
for the creation of a WindowIdentifier on X11 without bringing in
the extra dependencies required for the `raw_handle` feature.

Better support for WindowIdentifiers on x11.

---

Cargo.toml

Should let ashpd build on 32-bit architectures with glibc and gets it closer to building on 32-bit architectures with musl.

Update pipewire to 0.5

---

Cargo.toml
src/window_identifier/mod.rs

It is not possible to construct a display for a surface, the user has to
specify it.

Fix from_raw_handle for wayland-rs 0.30.0.beta.8

---

src/desktop/remote_desktop.rs

The KeyState enum for the RemoteDesktopProxy incorrectly maps "Pressed" to 0 and "Released" to 1 when it should be the other way around. (see [here](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-RemoteDesktop.NotifyKeyboardKeycode))
This PR fixes that.

Fix incorrect KeyState mapping in RemoteDesktopProxy

---

src/desktop/global_shortcuts.rs
src/desktop/mod.rs

Draft because I don't have the setup to test it yet, and it needs some better docs.
~~EDIT: Turns out that it also wrongfully assumes that there is only one `Vec<Shortcut>` type, while in reality there is two, one for defining new shortcuts and one for reading them, so this is also TODO.~~

Add global shortcuts implementation

---

ashpd-demo/src/portals/mod.rs

This was giving files = [] if they were single letter files.

demo: Fix files in SaveFiles

---

Cargo.toml

Fixes the compilation errors with pipewire 0.3.64 / 0.3.65 (#118).

Bump pipewire crate to 0.6

---

ashpd-demo/Cargo.lock
ashpd-demo/Cargo.toml

Fixes
```
error[E0425]: cannot find function `pipewire_streams` in module `camera`
--> src/portals/desktop/camera.rs:96:39
|
96 |                 let streams = camera::pipewire_streams(stream_fd).await.unwrap();
|                                       ^^^^^^^^^^^^^^^^ not found in `camera`
```
Missing the `Cargo.lock` changes though, see #149

demo: enable the ashpd pipewire feature

---

src/window_identifier/gtk4.rs

static is like a const that can be mutated, we dont need that.

window_identifier: Use const rather than static

---

Cargo.toml

A typo in `Cargo.toml` seems to be the cause of docs.rs [build failure](https://docs.rs/crate/ashpd/latest).

Fix docs.rs

---

src/flatpak/mod.rs

The first change is that `Spawn` is not about running things outside the sandbox but inside. There is a different interface for running processes outside of the sandbox.
The second one is an all-to-common typo of writing `existed` instead of `exited`. This does break API but it also fixes it so I don't know what you'd want to do about accepting that. Maybe the typoed version should be deprecated instead?

Correct a comment and a typo

---

src/window_identifier/gtk4.rs
src/window_identifier/mod.rs

Do not require gtk4 feature to be enabled for
WindowIdentifier::from_native to allow to use this feature with only wayland enabled.
Closes #171

window_identifier: from_native with wayland only

---

src/flatpak/development.rs
src/flatpak/mod.rs
src/proxy.rs

This is a lot like spawn but you sometimes need to run programs from the host system. This is e.g. used by GNOME Builder to run flatpak itself to build your stuff.
I don't know how much sense it makes to get the demo app to use this as it would require adding host filesystem access for it to really show something.

flatpak: add the Development interface to launch programs on the host

---

src/proxy.rs

When multiple tasks are trying to create proxies simultaneously, another task may initialize the zbus-Connection-OnceCell while the connection is initialized.
This ensures that only the first task to establish a connection initializes the OnceCell
Fixes #185

Fix possible OnceCell panic in Proxy::connection()

---

Cargo.toml
src/desktop/secret.rs
src/helpers.rs

The async-std crate didn't had a release for 1 1/2 years. It also pulls in a lot of dependencies that are usually not needed. The Path::exists() feature of async-std is just using spawn_blocking around the std metadata function and therefore settling on a specific executor and spawning a bunch of threads that might not be needed.
Therefore I replaced all uses of async-std with the crates from which async-std is build and that are well maintained.

Drop async-std crate

---

src/desktop/settings.rs

Fixes an issue, where [contrast settings](https://docs.rs/ashpd/0.7.0/ashpd/desktop/settings/enum.Contrast.html) have the wrong documentation.

desktop/settings: fix contrast docs

---

src/desktop/color.rs
src/desktop/settings.rs

I believe the accent color is defined [here](https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.impl.portal.Settings.xml) . Without the patch, it panics trying to parse the value, but maybe I've misinterpreted the type defined in the xml.

0.7 accent

---

src/desktop/input_capture.rs

Fix deserialization in input_capture portal

---

src/activation_token/mod.rs
src/desktop/dynamic_launcher.rs
src/desktop/email.rs
src/desktop/open_uri.rs
src/lib.rs

Allow manually setting the `activation_token` option for the [OpenURI](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.OpenURI.html) and [DynamicLauncher.Launch](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.DynamicLauncher.html#org-freedesktop-portal-dynamiclauncher-launch) portals.
I saw that https://github.com/bilelmoussaoui/ashpd/pull/70 is opened but it also includes additional integration, while this just allows setting the token if we already got it from somewhere else (e.g. directly via the Wayland protocol)
(related commit: https://github.com/apricotbucket28/zed/commit/15489a03966b1c627c9596e0635c5f45c9411b9e)

Allow setting activation_token in supported portals

---

src/desktop/input_capture.rs

The spec states "options - Vardict with **_optional_** further information".
As of right now, the KDE portal does not send a `barrier_id` in the Activated signal, which breaks deserialization...
I'm proposing this change, which makes all of the fields optional.
Technically this implementation is also wrong with most other signals, but let me know, what you think about this.

make activation-options optional

---

src/desktop/input_capture.rs

@bilelmoussaoui 
#218  the 2nd
Everything that could break deserialization should now be covered.
I left the Options controlled by us non-optional (like the handle_token / session_handle_token in create-session) because they can not break anything (they are only _serialized_ but not _deserialized_).
I'm a bit unsure about the `ZonesChanged` Signal, as `None` does not seem to make sense but according to the docs it is optional as well.
Would be good, if you could double check that I didnt miss anything ;)

desktop/input-capture: make options Option<T>

---

src/desktop/file_chooser.rs

While investigating why the open directory dialogs in Zed weren't the same as other GTK programs and Chromium, I noticed that the dbus message ashpd sent had an empty choices array (even though Zed didn't set any choices itself). Making the choices optional so ashpd wouldn't send them fixed the problem.
This is probably a KDE quirk; but the [file chooser](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html) portal documentation states:
> As a special case, passing an empty array for the list of choices indicates a boolean choice that is typically displayed as a check button, using “true” and “false” as the choices.
So it's probably a good idea to make them optional.
To clarify, this is what dialogs looked like before:
And this is how they look …

file_chooser: Make choices optional

---

src/desktop/global_shortcuts.rs
src/desktop/inhibit.rs
src/desktop/input_capture.rs
src/desktop/location.rs
src/desktop/mod.rs
src/desktop/remote_desktop.rs
src/desktop/screencast.rs
src/desktop/session.rs
src/lib.rs

Make the `SessionPortal` trait public so that users can use it in trait bounds.
For example I'd like to have a newtype around Session that calls `close` on Drop. Currently I can't do that in a generic way, because I can't use the trait as a bound since it's private.
```rust
struct CloseOnDrop<'s, Portal: ashpd::desktop::session::SessionPortal>(Session<'s, Portal>);
impl<P: ashpd::desktop::session::SessionPortal> Drop for CloseOnDrop<'_, P> {
fn drop(&mut self) {
pollster::block_on(self.0.close());
}
}
```
```
error[E0603]: module `session` is private
--> src/backend/connection.rs:192:25
|
192 | impl<P: ashpd::desktop::session::SessionPortal> Drop for CloseOnDrop<'_, P> {
|                         ^^^^^^^  ------------- trait `SessionPortal` is not publicly re-exported
| …
```

desktop: Make trait SessionPortal public

---

src/desktop/device.rs
src/desktop/game_mode.rs
src/flatpak/development.rs
src/flatpak/mod.rs
src/lib.rs

As per the documentation, methods which accept pids (e.g. `RegisterGame`, `RegisterGameByPid`) require the type of pid to be `i` (`i32`), not `u` (`u32`).
Using `u32` causes errors in runtime, making these methods unusable. This bug was most likely introduced by ae81250.
See https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.GameMode.html

desktop/game_mode: Use `i32` for pid

---

src/lib.rs

If is_sandobx is called multiple times, there can be a race condition with the initial check. Use get_or_init to always return the same result from the function.

is_sandboxed: Don't unwrap OnceCell set

---

src/desktop/input_capture.rs

According to the documentation, barrier-ids must be non-zero.
(https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.InputCapture.html#org-freedesktop-portal-inputcapture-setpointerbarriers)

fix barrier_id=0 in input-capture example

---

Cargo.toml
src/desktop/input_capture.rs

The API `reis` provides could still be improved, but it's a bit simpler to use.

Update `reis` to 0.4, with more concise API

---

src/desktop/game_mode.rs
src/desktop/open_uri.rs
src/desktop/print.rs
src/desktop/secret.rs
src/desktop/trash.rs
src/desktop/wallpaper.rs
src/documents/file_transfer.rs
src/documents/mod.rs
src/flatpak/development.rs
src/flatpak/mod.rs

This is more general, in particular the following will still compile.
```rust
let fd = something_implementing_as_fd;
let fd: &std::os::fd::BorrowedFd<'_> = &fd.as_fd();
ashpd::any_method_using_a_fd(fd).await?;
```

Take impl AsFd instead of BorrowedFd

---

Cargo.toml
src/activation_token/gtk4.rs
src/activation_token/mod.rs

cc @jsparber
I noticed that `cargo clippy --features=gtk4 -- -W clippy::pedantic` will complain:
```
warning: casting from `*const glib::Class<gtk4::gdk4::AppLaunchContext>` to a more-strictly-aligned pointer (`*mut gtk4::gio::gio_sys::GAppLaunchContextClass`) (1 < 8 bytes)
--> src/activation_token/mod.rs:63:17
|
63 |                 std::ptr::addr_of!((*context.class().parent()?)) as *mut _;
|                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cast_ptr_alignment
= note: `-W clippy::cast-ptr-alignment` implied by `-W clippy::pedantic`
= help: to override `-W clippy::pedantic` add `#[allow(clippy::cast_ptr_alignment)]`
```

activation_token: Provide GTK 4 helper

---

src/activation_token/gtk4.rs

Use as const as mut, this fixes a clippy lint that could have been seen with
cargo clippy --features=gtk4 -- -W clippy::cast-ptr-alignment

fixup! activation_token: Provide GTK 4 helper

---

ashpd-demo/src/application.rs

I was told to run `cargo +nightly fmt` to format the code in my PR and this keeps popping.
(from commit b61d118bb3599c77ab7b0b5d9a6926e757fdc405)

rust: Run cargo +nightly fmt

---

.typos.toml
Cargo.toml
README.md
examples/screen_cast_pw.rs
src/desktop/camera.rs
src/desktop/screencast.rs

feat: add screen cast with pipewire example

---

ashpd-demo/build-aux/com.belmoussaoui.ashpd.demo.Devel.json
ashpd-demo/data/resources/ui/file_chooser.ui
ashpd-demo/src/portals/desktop/file_chooser.rs

Add a combox box that allows select different filters to the OpenFile and SaveFile dialogs. Adding different mime types allows for some flexibility when testing e.g. file choser implementations.
When a filter set of filters is selected we pick the first filter as the `current_filter`.
The default is no filters.
A separate commit avoids a redirect when cloning libshumate
Screenshot:

demo: Allow to set file chooser filters

---

backend-demo/src/account.rs
backend-demo/src/screenshot.rs
backend-demo/src/secret.rs
backend-demo/src/settings.rs
backend-demo/src/wallpaper.rs
src/backend/access.rs
src/backend/account.rs
src/backend/app_chooser.rs
src/backend/background.rs
src/backend/email.rs
src/backend/file_chooser.rs
src/backend/print.rs
src/backend/request.rs
src/backend/screenshot.rs
src/backend/secret.rs
src/backend/wallpaper.rs
src/desktop/handle_token.rs
src/desktop/mod.rs

In the current state of `ashpd::backend`, it is difficult to associate each request with the backend logic. So any further calls on the request is left in ambiguity.
For example, let's say two apps call `Account.GetUserInformation`. Our implementation shows dialogs that lets the user enter their details. Now, if one of these apps cancel their request with `Request.close()`, then it is impossible (or difficult) for implementer to know which dialog must be closed.
An easy fix to this problem is to pass the object path of request on the method calls. Now the backend can associate each request with its backend logic, like say a hash map of requests to dialogs. Then, when `close` method is called, it can identify which dialog to close and can close it.
I'm a Rust newbie, so not sure if …

backend: Pass handle token to method calls for easier identification and association with their backend logic

---

src/lib.rs

Shows a compiler warning when neither tokio nor async-std are enabled. When both features are disabled, the project fails to compile, as the symbols cannot be resolved.

feat: error when neither tokio nor async-std are enabled

---

src/desktop/print.rs

desktop/print: Various fixes

---

src/window_identifier/mod.rs

Closes #276.
Worth nothing that c implementations like `strtol` also trim `0X` prefixes, I didn't add it because I'm not aware of them being used anywhere and it's already just for compatibility

Don't prefix x11 window identifier with `0x`

---

backend-demo/data/ashpd-backend-demo.portal
backend-demo/src/access.rs
backend-demo/src/main.rs

Without it, the xdg-desktop-portal frontend will skip looking for an
implementation of the Screenshot and Wallpaper interfaces, among others
(see https://github.com/flatpak/xdg-desktop-portal/blob/2fb76ffb/src/xdg-desktop-portal.c#L321-L358).

backend-demo: Implement the Access interface

---

src/desktop/camera.rs
src/desktop/remote_desktop.rs
src/desktop/screencast.rs
src/documents/file_transfer.rs
src/error.rs

Make them valid permalinks that will always point to the intended piece of code.

Fix links to source code in comments and documentation

---

Cargo.lock
Cargo.toml
src/window_identifier/mod.rs

This is commonly required in backend implementations as the portal dialog has to be set as modal with respect to the original application that launched them.
Not sure if I understand the macros control flow properly, any suggestions on improvement is very much welcome.

window_identifier: Add `set_parent_of` method

---

Cargo.toml
backend-demo/Cargo.toml
src/backend/access.rs
src/backend/account.rs
src/backend/app_chooser.rs
src/backend/background.rs
src/backend/builder.rs
src/backend/email.rs
src/backend/file_chooser.rs
src/backend/lockdown.rs
src/backend/mod.rs
src/backend/permission_store.rs
src/backend/print.rs
src/backend/request.rs
src/backend/screencast.rs
src/backend/screenshot.rs
src/backend/secret.rs
src/backend/settings.rs
src/backend/spawn.rs
src/backend/usb.rs
src/backend/wallpaper.rs

Closes #278.
I've tested this using both tokio and a custom executor (gpui).
I'm not super happy with this, as it potentially introduces a bit of runtime overhead since the executor now has to be passed around and cloned. It would be possible to add feature flags to every place it's used and avoid that, but that adds a lot of noise to a lot of places - I'd be happy to do that though, if you're fine with that.
That way, it would also be possible to make the executor a required parameter on the builder, right now it errors at runtime when building the backend if you didn't pass a spawner and have `tokio` disabled.

Allow passing a custom future spawner to backend builder

---

Cargo.lock
Cargo.toml
src/desktop/handle_token.rs

Currently, `ashpd` uses both `fastrand` through `zbus->futures-lite->fastrand`, and `rand`.
Rand supports various abstractions for generators and distributions, but `ashpd` only has a very basic use case of generating a simple token.
By switching to `fastrand` we can cut a few dependencies:
```
Removing ppv-lite86 v0.2.21
Removing rand v0.9.2
Removing rand_chacha v0.9.0
Removing rand_core v0.9.3
Removing zerocopy v0.8.26
Removing zerocopy-derive v0.8.26
```
Whether this actually saves time depends on how the remaining build looks like, but it doesn't hurt. On a clean release build of `ashpd` there isn't really a measurable speedup, but there's at least potential to skip the `1s` build (and build script) of `zerocopy`.

Switch from `rand` to `fastrand`
